# Generated by Django 4.1.7 on 2023-02-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('specialty', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RenameModel(
            old_name='Curso',
            new_name='Course',
        ),
        migrations.RenameModel(
            old_name='Entregable',
            new_name='Deliverable',
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.RenameField(
            model_name='course',
            old_name='camada',
            new_name='attendees',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='deliverable',
            old_name='entregado',
            new_name='delivered',
        ),
        migrations.RenameField(
            model_name='deliverable',
            old_name='fecha_entrega',
            new_name='due_date',
        ),
        migrations.RenameField(
            model_name='deliverable',
            old_name='nombre',
            new_name='name',
        ),
    ]
