# Generated by Django 4.1.7 on 2023-02-23 18:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('AppCoder', '0002_professor_students_rename_curso_course_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
    ]
