# Generated by Django 4.1.7 on 2023-02-26 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_rename_students_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name'], 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='deliverable',
            options={'ordering': ['name'], 'verbose_name_plural': 'Deliverables'},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name_plural': 'Professors'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name_plural': 'Students'},
        ),
        migrations.RemoveField(
            model_name='deliverable',
            name='delivered',
        ),
        migrations.AddField(
            model_name='course',
            name='professor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='AppCoder.professor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(to='AppCoder.student'),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='AppCoder.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliverable',
            name='professor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='AppCoder.professor'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='StudentDeliverables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered', models.BooleanField()),
                ('deliverable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCoder.deliverable')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCoder.student')),
            ],
        ),
    ]
