# Generated by Django 4.1.7 on 2023-02-26 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_squashed_0004_alter_course_options_alter_deliverable_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverable',
            name='professor',
        ),
        migrations.AlterField(
            model_name='course',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppCoder.professor'),
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(null=True, to='AppCoder.student'),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCoder.course'),
        ),
    ]
